### ISSUE TITLE
BCD Lang Element value cannot be read due to InvalidSizeField

### ISSUE THREAD

**Issue by SaphireLattice** [ColinFinck/nt-hive#5]
Trying to read a `12000005` Element of a BCD object results in the following error:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidSizeField { offset: 49144, expected: 8, actual: 4 }', src/main.rs:91:43
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
   2: core::result::unwrap_failed
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/result.rs:1749:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/result.rs:1065:23
   4: bcd_editor::main
             at ./src/main.rs:91:37
   5: core::ops::function::FnOnce::call_once
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

The actual field is around 5 symbols of lang code (ala "en_US")

**Comment by ColinFinck** [comment]
Thanks for reporting this bug! It took me a while, but I could finally reproduce it with a `BCD` file of mine.
Turns out that I previously had the cell size validation wrong. `BCD` registry hives often don't leave any unused space, so the bug primarily occurred there.
